version: '2'
services:
  webapp:
    build: ./webapp
    image: webapp:tag
    links: 
      - mysql 
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  mysql:
    image: mysql 
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=BucketList
      - MYSQL_PASSWORD=ibrahim
      - MYSQL_USER=ibrahim
    volumes:
      - /var/local/mysql/data:/var/lib/mysql 
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "33006:3306"
